109723 Support list of plants and list of object types as input parameters
equinor/procosys-fam-feeder-function pull request #32
Opened 2024-02-09 09:12 UTC by haavard-hoijord

AB#109723

2024-02-09 13:19 UTC, jsoi-eq commented on Core/Models/QueryParameters.cs
> +    public QueryParameters(string plants, string pcsTopics) : this(new List<string> { plants }, new List<string> { pcsTopics }) { }
Should the parameters be using singular here? I.e. plant and pcsTopic?

2024-02-09 13:25 UTC, jsoi-eq commented on Core/Services/FamFeederService.cs
> +                    _logger.LogInformation("found no events, or field is null");
Would be helpful to log which plant and topic we found 0 events for.

2024-02-09 13:26 UTC, jsoi-eq commented on Core/Services/FamFeederService.cs
> +                _logger.LogInformation("Finished sending {Topic} to fam",topic);
Extend this log statement to also include which plant

2024-02-09 13:30 UTC, jsoi-eq commented on Core/Services/FamFeederService.cs
> +        return $"finished successfully sending {mappedMessagesCount} messages to fam for {queryParameters.PcsTopics} and plants {queryParameters.Plants}";
Will this automatically write the PcsTopics and Plants List<string> as a comma separated list? 
Testing in dotnetfiddle seemed to indicate no?

2024-02-09 13:41 UTC, jsoi-eq commented on Core/Services/SearchFeederService.cs
> +            "Found {events} events for topic {topic} and plant {plant}",items.Count,queryParameters.PcsTopics,queryParameters.Plants);
Will the content PcsTopics and Plants lists be written, or the type name?

2024-02-09 13:41 UTC, jsoi-eq commented on Core/Services/SearchFeederService.cs
> +            _logger.LogInformation($"Sending {batchList.Count} items to Search Index {queryParameters.Plants} {queryParameters.PcsTopics}");
Will the content PcsTopics and Plants lists be written, or the type name?

2024-02-09 13:43 UTC, jsoi-eq commented on Core/Services/FamFeederService.cs
> +                returnEvents.AddRange(events);
I'm a little bit worried about the size of the returnEvents list, could this be millions big of json, what would the memory footprint be, any idea?

2024-02-09 13:51 UTC, jsoi-eq commented on FamFeederFunction/Functions/FamFeeder/TopicHttpTrigger.cs
> +        if (!topicsQuery.Any(s => TopicHelper.GetAllTopicsAsEnumerable().Contains(s, StringComparer.InvariantCultureIgnoreCase)))
I would like to gradually introduce more unit tests in the solution, this seems like a good candidate, my head always tilts when trying to parse linq queries like this...

2024-02-09 14:08 UTC, jsoi-eq commented on FamFeederFunction/Functions/FamFeeder/TopicOrchestrator.cs
>              return new List<string> { "Please provide a valid plant" };
Maybe change to something like "one or more plants are invalid" ?

2024-02-09 14:24 UTC, jsoi-eq commented on FamFeederFunction/Functions/FamFeeder/TopicOrchestrator.cs
> +            foreach (var newParam in param.PcsTopics
Move result of linq query to separate value. Then readers don't have to scrutinize the query carefully to determine whether this query and the one in line 48 are identical or not.

2024-02-09 14:46 UTC, jsoi-eq commented on FamFeederFunction/Functions/FamFeeder/TopicOrchestrator.cs
> -    private static async Task<List<string>> RunWoCutoffOrchestration(IDurableOrchestrationContext context, QueryParameters param)
Where did this method go? Was it subsumed into RunMultiPlantWoCutoffOrchestration as part of the code changes?

2024-02-09 14:47 UTC, jsoi-eq requested changes
See comments

2024-02-09 15:45 UTC, haavard-hoijord commented on Core/Services/FamFeederService.cs
> +                returnEvents.AddRange(events);
Well if you look at line 54 in the same file, the current useage of that function is running each plant+topic one at a time rather then running the entire list in one go so the memory footprint should be the same as before this PR. 

The function was just updated to work with the changed QueryParameters class incase it has another use in the future.

2024-02-09 15:47 UTC, haavard-hoijord commented on FamFeederFunction/Functions/FamFeeder/TopicOrchestrator.cs
>              return new List<string> { "Please provide a valid plant" };
If you mean just changing the log message then that is not how the if check is currently working, it would be the opposite where it checks if there are ANY valid plants, its not looking for any invalid plants

2024-02-09 15:49 UTC, haavard-hoijord commented on FamFeederFunction/Functions/FamFeeder/TopicOrchestrator.cs
> -    private static async Task<List<string>> RunWoCutoffOrchestration(IDurableOrchestrationContext context, QueryParameters param)
The function was no longer needed as it was just used whenever there was a single plant+topic while this PR makes it always use a list of plants and topics (even if there is just one plant and one topic)

2024-02-09 15:56 UTC, haavard-hoijord commented
Implemented some of the changes, still have the unit tests left to do.

2024-02-12 10:39 UTC, jsoi-eq commented on FamFeederFunction/Functions/FamFeeder/TopicOrchestrator.cs
>              return new List<string> { "Please provide a valid plant" };
Okay, we're back to my struggle with Linq. 
Could you extract the inside of the if ("!param.Plants.Any(s => allPlants.Contains(s, StringComparer.InvariantCultureIgnoreCase))"
to a separate method and give the method a descriptive name, then I would easier understand what the linq is trying to achieve.

2024-02-12 10:48 UTC, jsoi-eq commented on FamFeederFunction/Functions/FamFeeder/TopicHttpTrigger.cs
> +        if (!topicsQuery.Any(s => TopicHelper.GetAllTopicsAsEnumerable().Contains(s, StringComparer.InvariantCultureIgnoreCase)))
In the SplitList test, you could have values covering the different scenarios.
So in the unit test,  instead of 
var topics = "Action,Task,Tag";
something like
var topics = "  Action,  Task  ,Tag  , ,";
to cover scenarios for spaces, empty entries and comma separated to list.

2024-02-12 12:06 UTC, jsoi-eq approved these changes

2024-02-12 12:34 UTC, merged